/* global supabase */
'use strict';

const PAGE_SIZE = 10;
const MAX_FILES = 5;
const MAX_FILE_BYTES = 20 * 1024 * 1024;
const ALLOWED_EXTENSIONS = new Set(['jpg','jpeg','png','webp','gif','pdf','pptx','docx','xlsx']);
const ALLOWED_MIME = new Set([
  'image/jpeg','image/png','image/webp','image/gif','application/pdf',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
]);
const BOARDS = {
  notices:{title:'공지·일정',kicker:'NOTICE & SCHEDULE',description:'이달의 책, 모임 일정과 준비사항을 확인하세요.',table:'community_posts',kind:'notice'},
  resources:{title:'자료실',kicker:'CLUB RESOURCES',description:'워크북, 강의자료, AI 프롬프트와 다시보기를 모았습니다.',table:'community_posts',kind:'resource'},
  records:{title:'독서·실천 기록',kicker:'READ, ACT, GROW',description:'배운 점을 기록하고 실천 결과를 나눕니다.',table:'reading_records'},
  reviews:{title:'참여 후기',kicker:'MEMBER STORIES',description:'회원이 공개에 동의하고 운영자가 승인한 진짜 후기입니다.',table:'community_reviews'},
  inquiries:{title:'1:1 문의',kicker:'PRIVATE SUPPORT',description:'가입, 참여 방법과 자료 이용 문제를 안전하게 문의하세요.',table:'inquiries'}
};
const state={client:null,user:null,profile:null,board:'notices',page:1,search:'',items:[],count:0,detailId:null,adminMode:false,loginMode:false,composeMode:false};
const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];
const el=(tag,attrs={},children=[])=>{const node=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>{if(k==='class')node.className=v;else if(k==='text')node.textContent=v;else if(k.startsWith('on'))node.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==false&&v!=null)node.setAttribute(k,v===true?'':String(v));});[].concat(children).filter(Boolean).forEach(c=>node.append(c.nodeType?c:document.createTextNode(String(c))));return node;};
const fmt=(value,withTime=false)=>value?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',...(withTime?{hour:'2-digit',minute:'2-digit',hour12:false}:{})}).format(new Date(value)):'-';
const isAdmin=()=>state.profile?.role==='admin';
const isMember=()=>state.profile?.membership_status==='approved'||isAdmin();
const messageFor=(error)=>{const m=String(error?.message||error||'');if(/JWT|session|login|authenticated/i.test(m))return '로그인이 필요하거나 로그인 시간이 만료되었습니다.';if(/row-level|permission|policy|42501/i.test(m))return '이 작업을 할 권한이 없습니다.';if(/fetch|network/i.test(m))return '인터넷 연결을 확인한 뒤 다시 시도해 주세요.';return '처리하지 못했습니다. 잠시 후 다시 시도해 주세요.';};
function setState(message,type=''){const box=$('#board-state');box.className=`state-panel ${type}`;box.textContent=message;box.classList.remove('hidden');$('#board-list').classList.add('hidden');$('#pagination').classList.add('hidden');}
function currentReturnTo(){return `${location.pathname}${location.search}`;}
function safeReturnTo(value){return typeof value==='string'&&value.startsWith('/')&&!value.startsWith('//')?value:'/community/notices';}

async function init(){
  route(); bindBase(); configureMeta(); renderStaticBoard();
  try{
    const response=await fetch('/api/config',{cache:'no-store'});const config=await response.json();
    if(!response.ok||!config.configured)throw new Error(config.message||'not configured');
    state.client=supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
    const {data:{session}}=await state.client.auth.getSession();state.user=session?.user||null;
    state.client.auth.onAuthStateChange((_event,next)=>{state.user=next?.user||null;window.setTimeout(async()=>{await loadProfile();renderHeader();await loadRoute();},0);});
    await loadProfile();renderHeader();await loadRoute();
  }catch(error){
    $('#auth-button').disabled=true;$('#auth-button').title='게시판 연결 후 로그인할 수 있습니다.';
    $('#connection-state').textContent=error.message==='not configured'?'게시판 연결 준비 중입니다. 운영자에게 문의해 주세요.':(error.message||'게시판 연결 정보를 불러오지 못했습니다.');
    $('#connection-state').className='state-panel warning';
    if(state.adminMode){$('.board-shell').classList.add('hidden');$('#admin-view').classList.remove('hidden');$('#admin-content').textContent='Supabase 연결 후 관리자 기능을 사용할 수 있습니다.';}
    else setState('게시판 연결 전이라 내용을 불러올 수 없습니다.','warning');
  }
}
function renderStaticBoard(){if(state.adminMode)return;const b=BOARDS[state.board];$('#board-kicker').textContent=b.kicker;$('#board-title').textContent=b.title;$('#board-description').textContent=b.description;$('#faq-box').classList.toggle('hidden',state.board!=='inquiries');}
function route(){const parts=location.pathname.split('/').filter(Boolean);state.adminMode=parts[0]==='admin';state.loginMode=parts[0]==='community'&&parts[1]==='login';state.board=state.adminMode||state.loginMode?'notices':(parts[1]&&BOARDS[parts[1]]?parts[1]:'notices');const q=new URLSearchParams(location.search);state.page=Math.max(1,Number(q.get('page'))||1);state.search=(q.get('q')||'').slice(0,100);state.detailId=q.get('id');state.composeMode=q.get('new')==='1';}
function configureMeta(){const privatePage=state.adminMode||state.loginMode||['records','inquiries'].includes(state.board);$('meta[name="robots"]').content=privatePage?'noindex,nofollow':'index,follow';const b=BOARDS[state.board];const url=`https://aibookclub.kr/${state.adminMode?'admin/community':state.loginMode?'community/login':`community/${state.board}`}`;document.title=`${state.loginMode?'로그인':state.adminMode?'관리자':b.title} | 임헌수의 AI 독서클럽`;$('link[rel="canonical"]').href=url;$('meta[property="og:url"]').content=url;}
function bindBase(){
  $$('.board-tabs a').forEach(a=>a.classList.toggle('active',a.dataset.board===state.board));
  $('#search-input').value=state.search;$('#search-form').addEventListener('submit',e=>{e.preventDefault();const q=$('#search-input').value.trim();location.href=`/community/${state.board}${q?`?q=${encodeURIComponent(q)}`:''}`;});
  $('#auth-button').addEventListener('click',async()=>{if(state.user){await state.client.auth.signOut();location.href='/community/notices';}else openAuth();});
  $('.close-panel').addEventListener('click',()=>$('#auth-panel').classList.add('hidden'));
  $('#email-form').addEventListener('submit',sendOtp);$('#otp-form').addEventListener('submit',verifyOtp);$('#resend-code').addEventListener('click',sendOtp);
  $('#write-button').addEventListener('click',()=>showEditor());$$('.admin-tabs button').forEach(b=>b.addEventListener('click',()=>loadAdmin(b.dataset.admin)));
  window.addEventListener('popstate',()=>location.reload());
}
async function loadProfile(){state.profile=null;if(!state.user)return;const {data}=await state.client.from('profiles').select('id,display_name,membership_status,role').eq('id',state.user.id).maybeSingle();state.profile=data;}
function renderHeader(){const button=$('#auth-button');button.textContent=state.user?'로그아웃':'로그인';$('#admin-link').classList.toggle('hidden',!isAdmin());}
function openAuth(){sessionStorage.setItem('authReturnTo',currentReturnTo());$('#auth-panel').classList.remove('hidden');$('#auth-email').focus();}
async function sendOtp(event){event?.preventDefault();const email=$('#auth-email').value.trim();if(!email){$('#auth-message').textContent='이메일을 입력해 주세요.';return;}const btn=$('#email-form button');btn.disabled=true;const {error}=await state.client.auth.signInWithOtp({email,options:{shouldCreateUser:true}});btn.disabled=false;if(error){$('#auth-message').textContent=messageFor(error);return;}$('#email-form').classList.add('hidden');$('#otp-form').classList.remove('hidden');$('#auth-message').textContent='이메일로 인증코드를 보냈습니다. 코드가 보이지 않으면 스팸함을 확인해 주세요.';$('#auth-otp').focus();}
async function verifyOtp(event){event.preventDefault();const email=$('#auth-email').value.trim(),token=$('#auth-otp').value.trim();const btn=$('#otp-form button');btn.disabled=true;const {error}=await state.client.auth.verifyOtp({email,token,type:'email'});btn.disabled=false;if(error){$('#auth-message').textContent='코드가 올바르지 않거나 만료되었습니다. 다시 받아 주세요.';return;}location.href=safeReturnTo(sessionStorage.getItem('authReturnTo'));}
async function loadRoute(){if(state.loginMode){if(state.user){location.replace(isAdmin()?'/admin/community':'/community/notices');return;}openAuth();}if(state.adminMode){$('.board-shell').classList.add('hidden');$('#admin-view').classList.remove('hidden');if(!state.user){openAuth();$('#admin-content').textContent='관리자 로그인이 필요합니다.';return;}if(!isAdmin()){$('#admin-content').textContent='관리자만 이용할 수 있습니다.';return;}await loadAdmin('members');return;}renderStaticBoard();const write=$('#write-button');write.textContent=state.board==='notices'?'새 공지 작성':state.board==='resources'?'새 자료 등록':'글쓰기';write.classList.toggle('hidden',!canWrite());if(state.composeMode&&state.board==='notices'){showEditor();return;}if(state.detailId)await loadDetail(state.detailId);else await loadList();}
function canWrite(){if(['notices','resources'].includes(state.board))return isAdmin();if(['records','reviews'].includes(state.board))return isMember();if(state.board==='inquiries')return Boolean(state.user);return false;}
function requireWrite(){if(!state.user){openAuth();return false;}if(!canWrite()){setState(state.profile?.membership_status==='pending'?'회원 승인 후 이용할 수 있습니다.':'이 기능을 이용할 권한이 없습니다.','warning');return false;}return true;}

async function loadList(){
  if(state.board==='records'&&!isMember()){setState(state.user?'회원 승인 후 독서 기록을 볼 수 있습니다.':'로그인하고 회원 승인을 받은 뒤 이용할 수 있습니다.','warning');return;}
  if(state.board==='inquiries'&&!state.user){setState('로그인하면 본인이 작성한 문의와 답변만 확인할 수 있습니다.','warning');return;}
  setState('게시판을 불러오고 있습니다.');const b=BOARDS[state.board];let query=state.client.from(b.table).select('*',{count:'exact'});
  if(b.kind)query=query.eq('kind',b.kind);if(state.search)query=query.or(searchExpression());
  query=query.order(b.kind?'pinned':'created_at',{ascending:false}).order('created_at',{ascending:false}).range((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE-1);
  const {data,error,count}=await query;if(error){setState(messageFor(error),'error');return;}state.items=data||[];state.count=count||0;renderList();
}
function searchExpression(){const term=state.search.replace(/[%_,().]/g,' ').replace(/\s+/g,' ').trim();if(state.board==='records')return `book_title.ilike.%${term}%,learning.ilike.%${term}%`;if(state.board==='resources')return `title.ilike.%${term}%,description.ilike.%${term}%`;return `title.ilike.%${term}%,body.ilike.%${term}%`;}
function renderList(){const list=$('#board-list');list.replaceChildren();$('#result-count').textContent=`총 ${state.count.toLocaleString('ko-KR')}개`;if(!state.items.length){setState(state.search?'검색 결과가 없습니다.':'아직 등록된 글이 없습니다.');return;}$('#board-state').classList.add('hidden');list.classList.remove('hidden');state.items.forEach(item=>list.append(renderCard(item)));renderPagination();}
function renderCard(item){const title=item.title||item.book_title||'제목 없음';const excerpt=item.body||item.description||item.learning||item.content||'';const link=el('a',{class:'board-card',href:`/community/${state.board}?id=${item.id}`});const main=el('div');const badges=el('div',{class:'meta'});if(item.pinned)badges.append(el('span',{class:'pinned',text:'● 상단 고정'}));if(item.visibility)badges.append(el('span',{class:`badge ${item.visibility==='members'?'member':''}`,text:item.visibility==='members'?'회원 전용':'공개'}));if(item.record_type)badges.append(el('span',{class:'badge',text:labelRecord(item.record_type)}));if(state.board==='reviews')badges.append(el('span',{class:`badge ${item.approval_status==='approved'?'success':'pending'}`,text:item.approval_status==='approved'?'공개 승인':'승인 대기'}));if(state.board==='inquiries')badges.append(el('span',{class:`badge ${item.status==='answered'?'success':'pending'}`,text:item.status==='answered'?'답변 완료':'답변 대기'}));main.append(badges,el('h3',{text:title}),el('p',{class:'excerpt',text:excerpt}));const side=el('div',{class:'meta side'},[el('span',{text:item.public_display_name||item.display_name||''}),el('time',{text:fmt(item.created_at)})]);link.append(main,side);return link;}
function renderPagination(){const nav=$('#pagination');nav.replaceChildren();const pages=Math.ceil(state.count/PAGE_SIZE);if(pages<=1){nav.classList.add('hidden');return;}for(let p=1;p<=pages;p++){const q=new URLSearchParams();if(state.search)q.set('q',state.search);if(p>1)q.set('page',p);nav.append(el('button',{class:p===state.page?'active':'',text:p,onClick:()=>location.href=`/community/${state.board}?${q}`}));}nav.classList.remove('hidden');}

async function loadDetail(id){
  setState('글을 불러오고 있습니다.');const b=BOARDS[state.board];let query=state.client.from(b.table).select('*').eq('id',id);if(b.kind)query=query.eq('kind',b.kind);const {data:item,error}=await query.maybeSingle();if(error||!item){setState(error?messageFor(error):'글을 찾을 수 없거나 볼 권한이 없습니다.','error');return;}const view=$('#detail-view');view.replaceChildren();$('#board-state').classList.add('hidden');
  const title=item.title||item.book_title||'제목 없음';const top=el('div',{class:'meta'});if(item.visibility)top.append(el('span',{class:`badge ${item.visibility==='members'?'member':''}`,text:item.visibility==='members'?'회원 전용':'공개'}));if(item.record_type)top.append(el('span',{class:'badge',text:labelRecord(item.record_type)}));top.append(el('time',{text:fmt(item.created_at,true)}));view.append(top,el('h2',{text:title}));
  if(['notices','resources','reviews'].includes(state.board)&&item.visibility!=='members'&&(state.board!=='reviews'||(item.public_consent&&item.approval_status==='approved'))){document.title=`${title} | ${BOARDS[state.board].title} | AI 독서클럽`;$('meta[name="description"]').content=String(item.body||item.description||'AI 독서클럽 게시판').slice(0,150);const detailUrl=`https://aibookclub.kr/community/${state.board}?id=${encodeURIComponent(item.id)}`;$('link[rel="canonical"]').href=detailUrl;$('meta[property="og:url"]').content=detailUrl;$('meta[property="og:title"]').content=title;}
  if(state.board==='notices'){const grid=el('div',{class:'detail-grid'});if(item.book_title)grid.append(el('div',{text:`도서명: ${item.book_title}`}));if(item.meeting_at)grid.append(el('div',{text:`모임 일시: ${fmt(item.meeting_at,true)} (한국 시간)`}));if(grid.children.length)view.append(grid);}
  if(state.board==='resources'&&item.resource_type)view.append(el('p',{class:'badge',text:labelResource(item.resource_type)}));
  if(state.board==='records'){view.append(el('h3',{text:'배운 점'}),el('div',{class:'detail-body',text:item.learning}),el('h3',{text:'실천할 행동'}),el('div',{class:'detail-body',text:item.action_plan}));if(item.outcome)view.append(el('h3',{text:'실행 결과'}),el('div',{class:'detail-body',text:item.outcome}));}
  else view.append(el('div',{class:'detail-body',text:item.body||item.description||''}));
  if(item.external_url){const u=safeHttpUrl(item.external_url);if(u)view.append(el('a',{class:'button',href:u,target:'_blank',rel:'noopener noreferrer',text:'다시보기 열기'}));}
  await renderAttachments(view,item);const actions=el('div',{class:'actions'},[el('a',{class:'button button-secondary',href:`/community/${state.board}`,text:'목록'})]);if(canEdit(item))actions.append(el('button',{class:'button button-secondary',text:'수정',onClick:()=>showEditor(item)}),el('button',{class:'button button-danger',text:'삭제',onClick:()=>deleteItem(item)}));view.append(actions);
  if(state.board==='records')await renderComments(view,item);if(state.board==='inquiries')await renderInquiryReplies(view,item);if(['resources','reviews'].includes(state.board)&&(!item.visibility||item.visibility==='public'))view.append(el('a',{class:'button',href:'/community/inquiries',text:'독서클럽 참여 문의'}));
  view.classList.remove('hidden');
}
function canEdit(item){if(isAdmin())return true;if(['records','reviews','inquiries'].includes(state.board))return item.owner_id===state.user?.id;return false;}
async function renderAttachments(view,item){const {data}=await state.client.from('attachments').select('id,file_name,mime_type,size_bytes,storage_path').eq('target_type',targetType()).eq('target_id',item.id).order('created_at');if(!data?.length)return;const box=el('div',{class:'attachments'});for(const file of data){box.append(el('button',{type:'button',class:'attachment',onClick:()=>downloadFile(file)},[el('span',{text:file.file_name}),el('span',{text:formatBytes(file.size_bytes)})]));}view.append(el('h3',{text:'첨부파일'}),box);}
async function downloadFile(file){const {data,error}=await state.client.storage.from('community-private').createSignedUrl(file.storage_path,60,{download:file.file_name});if(error){alert(messageFor(error));return;}location.href=data.signedUrl;}
async function renderComments(view,item){const section=el('section',{class:'comments'},[el('h3',{text:'댓글'})]);const {data}=await state.client.from('record_comments').select('*').eq('record_id',item.id).order('created_at');(data||[]).forEach(c=>section.append(el('div',{class:'comment'},[el('div',{class:'meta',text:`${c.display_name} · ${fmt(c.created_at,true)}`}),el('p',{text:c.content})])));if(isMember()){const form=el('form',{class:'comment-form'},[el('input',{required:true,maxlength:'1000',placeholder:'댓글을 입력하세요',name:'content'}),el('button',{class:'button',type:'submit',text:'등록'})]);form.addEventListener('submit',async e=>{e.preventDefault();const button=$('button',form);button.disabled=true;const {error}=await state.client.from('record_comments').insert({record_id:item.id,content:new FormData(form).get('content'),display_name:state.profile?.display_name||'회원'});button.disabled=false;if(error)alert(messageFor(error));else location.reload();});section.append(form);}view.append(section);}
async function renderInquiryReplies(view,item){
  const section=el('section',{class:'comments'},[el('h3',{text:'운영자 답변'})]);
  const {data,error}=await state.client.from('inquiry_replies').select('id,body,created_at').eq('inquiry_id',item.id).order('created_at');
  if(error){
    section.append(el('p',{class:'muted',text:'답변을 불러오지 못했습니다.'}));
  }else if(!data?.length){
    section.append(el('p',{class:'muted',text:'아직 답변을 기다리고 있습니다.'}));
  }else{
    data.forEach(reply=>section.append(el('div',{class:'comment'},[
      el('div',{class:'meta',text:`운영자 · ${fmt(reply.created_at,true)}`}),
      el('p',{text:reply.body})
    ])));
  }
  view.append(section);
}

function showEditor(item=null){
  if(!requireWrite())return;$('#board-list').classList.add('hidden');$('#pagination').classList.add('hidden');$('#detail-view').classList.add('hidden');$('#board-state').classList.add('hidden');const view=$('#editor-view');view.replaceChildren(el('h2',{text:item?'글 수정':'새 글 작성'}));const form=el('form',{class:'editor-form'});buildFields(form,item);if(item)loadEditorAttachments(form,item);const files=el('input',{type:'file',name:'files',multiple:true,accept:'.jpg,.jpeg,.png,.webp,.gif,.pdf,.pptx,.docx,.xlsx'});form.append(el('label',{},['첨부파일',files,el('span',{class:'help',text:'이미지, PDF, PPTX, DOCX, XLSX · 파일당 20MB · 글 전체 최대 5개'})]));const msg=el('p',{class:'form-message'});const submit=el('button',{class:'button',type:'submit',text:item?'수정 저장':'등록'});form.append(msg,el('div',{class:'actions'},[submit,el('a',{class:'button button-secondary',href:item?`/community/${state.board}?id=${item.id}`:`/community/${state.board}`,text:'취소'})]));form.addEventListener('submit',e=>saveItem(e,item,msg,submit));view.append(form);view.classList.remove('hidden');scrollTo({top:0,behavior:'smooth'});
}
async function loadEditorAttachments(form,item){const holder=el('div',{class:'attachments'},[el('span',{class:'muted',text:'기존 첨부파일을 불러오는 중…'})]);form.append(holder);const {data,error}=await state.client.from('attachments').select('*').eq('target_type',targetType()).eq('target_id',item.id).order('created_at');holder.replaceChildren();if(error){holder.append(el('span',{class:'form-message',text:'기존 첨부파일을 불러오지 못했습니다.'}));return;}(data||[]).forEach(file=>holder.append(el('div',{class:'attachment'},[el('span',{text:file.file_name}),el('button',{type:'button',class:'button button-small button-danger',text:'파일 삭제',onClick:async()=>{if(!confirm(`${file.file_name} 파일을 삭제할까요?`))return;const removed=await state.client.storage.from('community-private').remove([file.storage_path]);if(removed.error){alert(messageFor(removed.error));return;}const deleted=await state.client.from('attachments').delete().eq('id',file.id);if(deleted.error)alert(messageFor(deleted.error));else{holder.remove();loadEditorAttachments(form,item);}}})])));if(!data?.length)holder.append(el('span',{class:'muted',text:'등록된 첨부파일이 없습니다.'}));}
function field(label,name,value='',type='text',required=true,options=[]){const input=type==='textarea'?el('textarea',{name,required,maxlength:'10000'}):type==='select'?el('select',{name,required}):el('input',{name,type,required,maxlength:type==='url'?'2048':'200'});if(type==='select')options.forEach(([v,t])=>input.append(el('option',{value:v,text:t})));if(type==='textarea')input.textContent=value||'';else input.value=value||'';return el('label',{},[label,input]);}
function buildFields(form,item={}){if(['notices','resources'].includes(state.board)){form.append(field('제목','title',item?.title));form.append(field(state.board==='notices'?'본문':'설명',state.board==='notices'?'body':'description',item?.body||item?.description,'textarea'));const row=el('div',{class:'two-col'});row.append(field('공개 범위','visibility',item?.visibility||'public','select',true,[['public','공개'],['members','회원 전용']]));if(state.board==='resources')row.append(field('자료 유형','resource_type',item?.resource_type||'workbook','select',true,[['workbook','워크북'],['lecture','강의자료'],['prompt','AI 프롬프트'],['replay','다시보기']]));form.append(row);if(state.board==='notices')form.append(el('div',{class:'two-col'},[field('도서명 (선택)','book_title',item?.book_title||'','text',false),field('모임 일시 (선택)','meeting_at',toLocalInput(item?.meeting_at),'datetime-local',false)]));else form.append(field('다시보기 링크 (선택)','external_url',item?.external_url||'','url',false));if(state.board==='notices')form.append(checkField('pinned','상단에 고정',item?.pinned));}
  if(state.board==='records'){form.append(field('말머리','record_type',item?.record_type||'reading','select',true,[['reading','독서 기록'],['practice','실천 인증'],['recommendation','책 추천']]));form.append(field('읽은 책','book_title',item?.book_title));form.append(field('배운 점','learning',item?.learning,'textarea'));form.append(field('실천할 행동','action_plan',item?.action_plan,'textarea'));form.append(field('실행 결과 (나중에 추가 가능)','outcome',item?.outcome||'','textarea',false));}
  if(state.board==='reviews'){form.append(field('후기 제목','title',item?.title));form.append(field('공개할 표시 이름','public_display_name',item?.public_display_name||state.profile?.display_name||''));form.append(field('참여 후기','body',item?.body,'textarea'));form.append(checkField('public_consent','홈페이지 공개에 동의합니다. (기본 미선택)',item?.public_consent));}
  if(state.board==='inquiries'){form.append(field('이름 또는 표시 이름','display_name',item?.display_name||state.profile?.display_name||''));form.append(field('문의 유형','inquiry_type',item?.inquiry_type||'join','select',true,[['join','가입 상담'],['participation','모임 참여'],['resource','자료 이용'],['other','기타']]));form.append(field('제목','title',item?.title));form.append(field('내용','body',item?.body,'textarea'));}}
function checkField(name,label,checked){const input=el('input',{type:'checkbox',name});input.checked=Boolean(checked);return el('label',{class:'check'},[input,el('span',{text:label})]);}
async function saveItem(event,item,msg,button){event.preventDefault();const form=event.currentTarget,files=[...form.elements.files.files];const existing=item?await state.client.from('attachments').select('id',{count:'exact',head:true}).eq('target_type',targetType()).eq('target_id',item.id):{count:0};const fileError=validateFiles(files,(existing.count||0)+files.length);if(fileError){msg.textContent=fileError;return;}button.disabled=true;msg.textContent='저장하고 있습니다…';try{const payload=payloadFrom(new FormData(form));const table=BOARDS[state.board].table;let result;if(item)result=await state.client.from(table).update(payload).eq('id',item.id).select().single();else result=await state.client.from(table).insert(payload).select().single();if(result.error)throw result.error;for(const file of files)await uploadAttachment(file,result.data.id);location.href=`/community/${state.board}?id=${result.data.id}`;}catch(error){msg.textContent=messageFor(error)+' 입력한 내용은 그대로 유지됩니다.';button.disabled=false;}}
function payloadFrom(fd){if(['notices','resources'].includes(state.board))return{kind:state.board==='notices'?'notice':'resource',title:String(fd.get('title')).trim(),body:state.board==='notices'?String(fd.get('body')).trim():null,description:state.board==='resources'?String(fd.get('description')).trim():null,visibility:fd.get('visibility'),pinned:fd.get('pinned')==='on',book_title:empty(fd.get('book_title')),meeting_at:empty(fd.get('meeting_at'))?new Date(fd.get('meeting_at')).toISOString():null,resource_type:empty(fd.get('resource_type')),external_url:empty(fd.get('external_url'))};if(state.board==='records')return{record_type:fd.get('record_type'),book_title:String(fd.get('book_title')).trim(),learning:String(fd.get('learning')).trim(),action_plan:String(fd.get('action_plan')).trim(),outcome:empty(fd.get('outcome'))};if(state.board==='reviews')return{title:String(fd.get('title')).trim(),body:String(fd.get('body')).trim(),public_display_name:String(fd.get('public_display_name')).trim(),public_consent:fd.get('public_consent')==='on'};return{display_name:String(fd.get('display_name')).trim(),inquiry_type:fd.get('inquiry_type'),title:String(fd.get('title')).trim(),body:String(fd.get('body')).trim()};}
async function uploadAttachment(file,targetId){const id=crypto.randomUUID(),safeName=file.name.normalize('NFKC').replace(/[^\p{L}\p{N}._-]+/gu,'_').slice(-120),path=`${state.user.id}/${targetType()}/${targetId}/${id}-${safeName}`;const uploaded=await state.client.storage.from('community-private').upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const inserted=await state.client.from('attachments').insert({target_type:targetType(),target_id:targetId,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size});if(inserted.error){await state.client.storage.from('community-private').remove([path]);throw inserted.error;}}
function validateFiles(files,totalCount=files.length){if(totalCount>MAX_FILES)return `첨부파일은 한 글에 최대 ${MAX_FILES}개까지 등록할 수 있습니다.`;for(const file of files){const ext=file.name.split('.').pop().toLowerCase();if(!ALLOWED_EXTENSIONS.has(ext)||!ALLOWED_MIME.has(file.type))return `${file.name}: 지원하지 않는 파일 형식입니다.`;if(file.size>MAX_FILE_BYTES)return `${file.name}: 파일당 20MB를 넘을 수 없습니다.`;}return '';}
async function deleteItem(item){if(!confirm('이 글과 연결된 첨부파일을 삭제할까요?'))return;const {data:files}=await state.client.from('attachments').select('storage_path').eq('target_type',targetType()).eq('target_id',item.id);if(files?.length){const removed=await state.client.storage.from('community-private').remove(files.map(f=>f.storage_path));if(removed.error){alert('첨부파일을 정리하지 못해 글 삭제를 중단했습니다.');return;}}const {error}=await state.client.from(BOARDS[state.board].table).delete().eq('id',item.id);if(error)alert(messageFor(error));else location.href=`/community/${state.board}`;}

async function loadAdmin(tab){$$('.admin-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.admin===tab));const box=$('#admin-content');box.textContent='불러오는 중…';if(tab==='members'){const {data,error}=await state.client.from('profiles').select('id,display_name,membership_status,role,created_at').order('created_at',{ascending:false});if(error){box.textContent=messageFor(error);return;}box.replaceChildren();(data||[]).forEach(p=>{const action=el('div',{class:'actions'});if(p.role!=='admin'){action.append(el('button',{class:'button button-small',text:p.membership_status==='approved'?'승인 해제':'회원 승인',onClick:()=>adminMembership(p.id,p.membership_status==='approved'?'revoked':'approved')}));}box.append(el('div',{class:'admin-row'},[el('div',{},[el('h3',{text:p.display_name||'표시 이름 미설정'}),el('div',{class:'meta',text:`${p.role==='admin'?'관리자':p.membership_status==='approved'?'승인 회원':'승인 대기/해제'} · ${fmt(p.created_at)}`})]),action]));});if(!data?.length)box.append(el('p',{class:'empty',text:'회원이 없습니다.'}));}
  if(tab==='reviews'){const {data,error}=await state.client.from('community_reviews').select('*').order('created_at',{ascending:false});if(error){box.textContent=messageFor(error);return;}box.replaceChildren();(data||[]).forEach(r=>box.append(el('div',{class:'admin-row'},[el('div',{},[el('h3',{text:r.title}),el('div',{class:'meta',text:`${r.public_display_name} · 공개동의 ${r.public_consent?'예':'아니오'} · ${r.approval_status}`})]),el('div',{class:'actions'},[el('a',{class:'button button-small button-secondary',href:`/community/reviews?id=${r.id}`,text:'보기'}),el('button',{class:'button button-small',text:'공개 승인',onClick:()=>adminReview(r.id,'approved')}),el('button',{class:'button button-small button-danger',text:'공개 중단',onClick:()=>adminReview(r.id,'rejected')})])])));}
  if(tab==='inquiries'){const {data,error}=await state.client.from('inquiries').select('*').order('created_at',{ascending:false});if(error){box.textContent=messageFor(error);return;}box.replaceChildren();(data||[]).forEach(i=>box.append(el('div',{class:'admin-row'},[el('div',{},[el('h3',{text:i.title}),el('div',{class:'meta',text:`${i.display_name} · ${i.status==='answered'?'답변 완료':'답변 대기'} · ${fmt(i.created_at)}`})]),el('div',{class:'actions'},[el('a',{class:'button button-small button-secondary',href:`/community/inquiries?id=${i.id}`,text:'보기'}),el('button',{class:'button button-small',text:'답변',onClick:()=>adminReply(i)})])])));}}
async function adminMembership(id,status){const {error}=await state.client.rpc('admin_set_membership',{target_user:id,next_status:status});if(error)alert(messageFor(error));else loadAdmin('members');}
async function adminReview(id,status){const {error}=await state.client.rpc('admin_review_decision',{review_id:id,decision:status});if(error)alert(messageFor(error));else loadAdmin('reviews');}
async function adminReply(item){const content=prompt(`문의: ${item.title}\n답변을 입력하세요.`);if(!content?.trim())return;const {error}=await state.client.rpc('admin_answer_inquiry',{inquiry_id:item.id,answer_body:content.trim()});if(error)alert(messageFor(error));else loadAdmin('inquiries');}

function targetType(){return{notices:'post',resources:'post',records:'record',reviews:'review',inquiries:'inquiry'}[state.board];}
function labelRecord(v){return{reading:'독서 기록',practice:'실천 인증',recommendation:'책 추천'}[v]||v;}
function labelResource(v){return{workbook:'워크북',lecture:'강의자료',prompt:'AI 프롬프트',replay:'다시보기'}[v]||v;}
function empty(value){const v=String(value||'').trim();return v||null;}
function safeHttpUrl(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function toLocalInput(value){if(!value)return'';const d=new Date(value),pad=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;return`${(n/1048576).toFixed(1)} MB`;}
if(typeof window!=='undefined')window.addEventListener('DOMContentLoaded',init);
if(typeof module!=='undefined')module.exports={validateFiles,safeReturnTo,safeHttpUrl,formatBytes};
